<a href="https://colab.research.google.com/github/Chukhlib/may/blob/main/lab4%2C%D0%A7%D1%83%D1%85%D0%BB%D1%96%D0%B1_%D0%9A%D0%B0%D1%80%D0%B8%D0%BD%D0%B0%2C%D0%92%D0%B0%D1%80%D1%96%D0%B0%D0%BD%D1%82_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'2.0.2'

In [ ]:
matrix=np.random.randint(1, 6, size=(3, 3))

matrix

array([[4, 5, 3],
       [3, 2, 1],
       [1, 4, 3]])

In [ ]:
det = np.linalg.det(matrix)
det

np.float64(-2.000000000000001)

In [ ]:
product = np.prod(matrix)
product

np.int64(4320)

In [ ]:
prod_1 = np.prod([0])
prod_2 = np.prod([1])
prod_3 = np.prod([2])
prod_1*prod_2*prod_3

np.int64(0)

In [ ]:
sum_1 = np.sum(matrix)

sum_1

np.int64(26)

In [ ]:
np.max(matrix)

np.int64(5)

In [ ]:
np.min(matrix)

np.int64(1)

In [ ]:
np.mean(matrix)

np.float64(2.888888888888889)

In [ ]:
max_element = np.max(matrix)

print("Найбільший елемент матриці:",max_element)

min_element = np.min(matrix)

print("Найменший елемент матриці:",min_element)

Найбільший елемент матриці: 5
Найменший елемент матриці: 1


In [ ]:
mean = np.mean(matrix)

print("Середнє значення елементів матриці:", mean)

Середнє значення елементів матриці: 2.888888888888889


In [ ]:
np.sqrt(matrix)

array([[2.        , 2.23606798, 1.73205081],
       [1.73205081, 1.41421356, 1.        ],
       [1.        , 2.        , 1.73205081]])

In [ ]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)

print("сума елементів кожного рядка")
print(row_sums)

сума елементів кожного рядка
[[12]
 [ 6]
 [ 8]]


In [ ]:
vector = np.random.randint(0, 10, size=25)

print("Початковий вектор")
print(vector)

# Сортуємо число за спаданням
sorted_vector = np.sort(vector)[::-1]

print("Вектор після сортування за спаданням")
print(sorted_vector)

Початковий вектор
[7 1 9 5 7 5 7 9 2 4 3 7 2 0 7 3 8 1 7 4 9 8 8 3 8]
Вектор після сортування за спаданням
[9 9 9 8 8 8 8 7 7 7 7 7 7 5 5 4 4 3 3 3 2 2 1 1 0]


In [ ]:
a = np.array([[14, 4, 6], [5, -3, 2], [10, -11, 5]])
b = np.array([30, 15, 36])

x = np.linalg.solve(a, b)
print('Вбудована функція', x)

inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print('Матричний метод', x1)

Вбудована функція [ 2. -1.  1.]
Матричний метод [ 2. -1.  1.]


In [ ]:
# Метод Крамера
def kramer(a, b):
    det_a = np.linalg.det(a)
    if det_a != 0:
        solutions = []
        for i in range(len(a)):
            modified_a = np.copy(a)
            modified_a[:, i] = b
            solutions.append(round(np.linalg.det(modified_a) / det_a, 1))

        print('Solving a system of linear algebraic equations by Cramer\'s method:')
        #print('x =', solutions)

    else:
        print('Determinant equals zero, the system has no solutions')
    return solutions
# Виклик функцій для розв'язання системи
print(kramer(a, b))

Solving a system of linear algebraic equations by Cramer's method:
[np.float64(2.0), np.float64(-1.0), np.float64(1.0)]
